---
# Handlers for raid_setup role

- name: update initramfs
  ansible.builtin.command: "{{ initramfs_update_cmd }}"
  vars:
    initramfs_update_cmd: >-
      {% if ansible_os_family == 'Debian' %}
      update-initramfs -u
      {% elif ansible_os_family == 'RedHat' %}
      dracut --force
      {% elif ansible_os_family == 'Suse' %}
      mkinitrd
      {% else %}
      true
      {% endif %}
